// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHkzb0pIh7HLHahBcRarXnqtUxR7gKRe0',
    appId: '1:338197364045:web:050ad78e0cbc6859e90b04',
    messagingSenderId: '338197364045',
    projectId: 'bionexus-7dda4',
    authDomain: 'bionexus-7dda4.firebaseapp.com',
    storageBucket: 'bionexus-7dda4.appspot.com',
    measurementId: 'G-MB4JQPFHYH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcX0DV3mPMbwa8Z9cJX5bZRjPOmDXKjHM',
    appId: '1:338197364045:android:d89473de54d7e6dce90b04',
    messagingSenderId: '338197364045',
    projectId: 'bionexus-7dda4',
    storageBucket: 'bionexus-7dda4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1HNFmK1mwHuTFJ58HBL4M5aHl_kyAgC0',
    appId: '1:338197364045:ios:5139f01808427f02e90b04',
    messagingSenderId: '338197364045',
    projectId: 'bionexus-7dda4',
    storageBucket: 'bionexus-7dda4.appspot.com',
    iosBundleId: 'com.example.bionexusAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1HNFmK1mwHuTFJ58HBL4M5aHl_kyAgC0',
    appId: '1:338197364045:ios:a30f96686ea61dc6e90b04',
    messagingSenderId: '338197364045',
    projectId: 'bionexus-7dda4',
    storageBucket: 'bionexus-7dda4.appspot.com',
    iosBundleId: 'com.example.bionexusAdmin.RunnerTests',
  );
}


